// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x010 : Data signal of vram_V
//         bit 31~0 - vram_V[31:0] (Read/Write)
// 0x014 : reserved
// 0x018 : Data signal of centerX_V
//         bit 31~0 - centerX_V[31:0] (Read/Write)
// 0x01c : Data signal of centerX_V
//         bit 31~0 - centerX_V[63:32] (Read/Write)
// 0x020 : Data signal of centerX_V
//         bit 31~0 - centerX_V[95:64] (Read/Write)
// 0x024 : reserved
// 0x028 : Data signal of centerY_V
//         bit 31~0 - centerY_V[31:0] (Read/Write)
// 0x02c : Data signal of centerY_V
//         bit 31~0 - centerY_V[63:32] (Read/Write)
// 0x030 : Data signal of centerY_V
//         bit 31~0 - centerY_V[95:64] (Read/Write)
// 0x034 : reserved
// 0x038 : Data signal of zoomHeight_V
//         bit 31~0 - zoomHeight_V[31:0] (Read/Write)
// 0x03c : Data signal of zoomHeight_V
//         bit 31~0 - zoomHeight_V[63:32] (Read/Write)
// 0x040 : Data signal of zoomHeight_V
//         bit 31~0 - zoomHeight_V[95:64] (Read/Write)
// 0x044 : reserved
// 0x048 : Data signal of updateColorMap
//         bit 7~0 - updateColorMap[7:0] (Read/Write)
//         others  - reserved
// 0x04c : reserved
// 0x200 ~
// 0x3ff : Memory 'colorMap' (384 * 8b)
//         Word n : bit [ 7: 0] - colorMap[4n]
//                  bit [15: 8] - colorMap[4n+1]
//                  bit [23:16] - colorMap[4n+2]
//                  bit [31:24] - colorMap[4n+3]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMANDELBROT_AXILITES_ADDR_AP_CTRL             0x000
#define XMANDELBROT_AXILITES_ADDR_GIE                 0x004
#define XMANDELBROT_AXILITES_ADDR_IER                 0x008
#define XMANDELBROT_AXILITES_ADDR_ISR                 0x00c
#define XMANDELBROT_AXILITES_ADDR_VRAM_V_DATA         0x010
#define XMANDELBROT_AXILITES_BITS_VRAM_V_DATA         32
#define XMANDELBROT_AXILITES_ADDR_CENTERX_V_DATA      0x018
#define XMANDELBROT_AXILITES_BITS_CENTERX_V_DATA      96
#define XMANDELBROT_AXILITES_ADDR_CENTERY_V_DATA      0x028
#define XMANDELBROT_AXILITES_BITS_CENTERY_V_DATA      96
#define XMANDELBROT_AXILITES_ADDR_ZOOMHEIGHT_V_DATA   0x038
#define XMANDELBROT_AXILITES_BITS_ZOOMHEIGHT_V_DATA   96
#define XMANDELBROT_AXILITES_ADDR_UPDATECOLORMAP_DATA 0x048
#define XMANDELBROT_AXILITES_BITS_UPDATECOLORMAP_DATA 8
#define XMANDELBROT_AXILITES_ADDR_COLORMAP_BASE       0x200
#define XMANDELBROT_AXILITES_ADDR_COLORMAP_HIGH       0x3ff
#define XMANDELBROT_AXILITES_WIDTH_COLORMAP           8
#define XMANDELBROT_AXILITES_DEPTH_COLORMAP           384

