// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmandelbrot.h"

extern XMandelbrot_Config XMandelbrot_ConfigTable[];

XMandelbrot_Config *XMandelbrot_LookupConfig(u16 DeviceId) {
	XMandelbrot_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMANDELBROT_NUM_INSTANCES; Index++) {
		if (XMandelbrot_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMandelbrot_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMandelbrot_Initialize(XMandelbrot *InstancePtr, u16 DeviceId) {
	XMandelbrot_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMandelbrot_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMandelbrot_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

